@extends('promethee::layout')
@section('title','Compagnies')
@section('content')
<div class="ops-header compact"><div><span class="eyebrow">ADMINISTRATION</span><h1>Compagnies.</h1><p>Le catalogue des compagnies est désormais éditable dans Prométhée.</p></div><span class="tag">{{ $airlines->count() }} affichée(s)</span></div>
<section class="panel"><form method="get" class="flight-filter"><label class="filter-wide">Recherche<input name="q" value="{{ request('q') }}" placeholder="Nom, ICAO, IATA ou indicatif"></label><label>État<select name="active"><option value="all">Toutes</option><option value="active" @selected(request('active')==='active')>Actives</option><option value="inactive" @selected(request('active')==='inactive')>Inactives</option></select></label><button>Filtrer</button><a class="button outline" href="{{ route('admin.promethee.airlines') }}">Réinitialiser</a></form></section>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">CRÉER OU MODIFIER</span><h2>Fiche compagnie</h2></div></div><form method="post" enctype="multipart/form-data" action="{{ route('admin.promethee.airlines.save') }}" class="form-grid" id="airline-form">@csrf<input type="hidden" name="id" id="airline-id"><label>ICAO<input name="icao" id="airline-icao" maxlength="5" required></label><label>IATA<input name="iata" id="airline-iata" maxlength="5"></label><label>Nom<input name="name" id="airline-name" required></label><label>Indicatif radio<input name="callsign" id="airline-callsign"></label><label>Pays<select name="country" id="airline-country"><option value="">—</option>@foreach($countries as $code=>$country)<option value="{{ $code }}">{{ $country }}</option>@endforeach</select></label><label>Logo (URL ou chemin existant)<input type="text" name="logo" id="airline-logo" placeholder="https://… ou airline-logos/logo.png"></label><label>Importer un logo<input type="file" name="logo_upload" id="airline-logo-upload" accept="image/png,image/jpeg,image/webp"><small>PNG, JPG ou WebP · 2 Mo max. L’import remplace l’URL renseignée.</small></label><div class="airline-logo-preview"><span class="eyebrow">APERÇU</span><img id="airline-logo-preview" alt="" hidden><span id="airline-logo-empty">Aucun logo sélectionné</span></div><label>Accès à partir de<input type="number" min="0" name="min_flight_hours" id="airline-min_flight_hours" value="0"><small>heures de vol validées</small></label><label><input type="checkbox" name="active" value="1" id="airline-active" checked> Active</label><div><button id="airline-submit">Créer la compagnie</button><button type="button" class="button outline" id="airline-reset">Nouvelle fiche</button></div></form></section>
<section class="panel table-wrap"><table><thead><tr><th>Nom</th><th>Codes</th><th>Indicatif</th><th>Pays</th><th>Accès pilote</th><th>État</th><th></th></tr></thead><tbody>@forelse($airlines as $airline)<tr><td><div class="airline-admin-identity">@if($airline->logo)<img src="{{ filter_var($airline->logo,FILTER_VALIDATE_URL) ? $airline->logo : asset(ltrim($airline->logo,'/')) }}" alt="">@endif<div><strong>{{ $airline->name }}</strong></div></div></td><td>{{ $airline->icao }}@if($airline->iata) · {{ $airline->iata }}@endif</td><td>{{ $airline->callsign ?: '—' }}</td><td>{{ $airline->country ?: '—' }}</td><td><strong>{{ number_format($airline->min_flight_hours) }} h</strong></td><td><span class="tag">{{ $airline->active ? 'Active' : 'Inactive' }}</span></td><td><a class="button outline" href="{{ route('admin.promethee.airlines.edit',$airline) }}">Modifier la compagnie →</a></td></tr>@empty<tr><td colspan="7">Aucune compagnie.</td></tr>@endforelse</tbody></table></section>
@push('scripts')<script>window.addEventListener('load',()=>{const form=document.getElementById('airline-form'),fields=['id','icao','iata','name','callsign','country','logo','active','min_flight_hours'].reduce((out,key)=>({...out,[key]:document.getElementById(`airline-${key}`)}),{});document.querySelectorAll('.edit-airline').forEach(button=>button.addEventListener('click',()=>{const item=JSON.parse(button.dataset.airline);Object.entries(item).forEach(([key,value])=>{if(key==='active')fields[key].checked=!!value;else fields[key].value=value??''});document.getElementById('airline-submit').textContent='Enregistrer les modifications';form.scrollIntoView({behavior:'smooth',block:'center'})}));const preview=document.getElementById('airline-logo-preview'),empty=document.getElementById('airline-logo-empty'),upload=document.getElementById('airline-logo-upload');const showPreview=src=>{if(src){preview.src=src;preview.hidden=false;empty.hidden=true}else{preview.removeAttribute('src');preview.hidden=true;empty.hidden=false}};fields.logo.addEventListener('input',()=>showPreview(fields.logo.value));upload.addEventListener('change',()=>{const file=upload.files?.[0];if(file)showPreview(URL.createObjectURL(file))});document.querySelectorAll('.edit-airline').forEach(button=>button.addEventListener('click',()=>{const item=JSON.parse(button.dataset.airline);if(item.logo)showPreview(/^https?:\/\//i.test(item.logo)?item.logo:'/'+item.logo)}));document.getElementById('airline-reset').addEventListener('click',()=>{form.reset();showPreview('');fields.id.value='';fields.active.checked=true;document.getElementById('airline-submit').textContent='Créer la compagnie'})});</script>@endpush
@endsection

@push('styles')<style>.airline-logo-preview{min-height:110px;border:1px dashed var(--line);padding:12px;display:grid;place-items:center;gap:8px}.airline-logo-preview img{max-width:180px;max-height:70px;object-fit:contain}.airline-admin-identity{display:flex;align-items:center;gap:10px}.airline-admin-identity img{width:54px;height:34px;object-fit:contain;background:#fff;border:1px solid var(--line);padding:3px}@media(max-width:680px){.airline-admin-identity img{width:44px}}</style>@endpush
