@extends('promethee::layout')
@section('title','Affectations mensuelles')
@section('content')
<div class="ops-header compact"><div><span class="eyebrow">ADMINISTRATION</span><h1>Affectations mensuelles.</h1><p>Filtrez, sélectionnez et gérez les lignes sans perdre le contexte du pilote ou du vol.</p></div><span class="tag">{{ $assignments->count() }} affichée(s)</span></div>
<section class="panel"><form method="get" class="flight-filter"><label>Mois<input type="month" name="month" value="{{ $month }}"></label><label class="filter-wide">Recherche<input name="q" value="{{ request('q') }}" placeholder="Pilote, numéro de vol, route ou aéroport"></label><label>Pilote<select name="pilot"><option value="">Tous</option>@foreach($pilots as $pilot)<option value="{{ $pilot->id }}" @selected((string) request('pilot') === (string) $pilot->id)>{{ $pilot->pilot_id }} · {{ $pilot->name }}</option>@endforeach</select></label><label>Ligne<select name="route"><option value="">Toutes</option>@foreach($assignments->pluck('route_code')->filter()->unique()->sort() as $route)<option value="{{ $route }}" @selected(request('route') === $route)>{{ $route }}</option>@endforeach</select></label><button>Filtrer</button><a class="button outline" href="{{ route('admin.promethee.assignments',['month'=>$month]) }}">Réinitialiser</a></form></section>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">NOUVEL OBJECTIF</span><h2>Attribuer une ligne</h2></div></div><form method="post" action="{{ route('admin.promethee.assignments.save') }}" class="form-grid">@csrf<input type="hidden" name="month" value="{{ $month }}"><label>Pilote<select name="user_id" required>@foreach($pilots as $pilot)<option value="{{ $pilot->id }}">{{ $pilot->pilot_id }} · {{ $pilot->name }}</option>@endforeach</select></label><label>Vol<select name="flight_id" required>@foreach($flights as $flight)<option value="{{ $flight->id }}">{{ $flight->route_code ?: $flight->flight_number }} · {{ $flight->dpt_airport_id }} → {{ $flight->arr_airport_id }}</option>@endforeach</select></label><label class="full">Note<textarea name="notes" rows="2"></textarea></label><button>Attribuer</button></form></section>
<form id="bulk-assignments" method="post" action="{{ route('admin.promethee.assignments.bulk-delete') }}" onsubmit="return confirm('Supprimer les affectations sélectionnées ?')">@csrf @method('DELETE')<section class="panel table-wrap"><div class="panel-heading"><div><span class="eyebrow">RÉSULTATS</span><h2>Détail des lignes</h2></div><button class="button outline" id="delete-selected" disabled>Supprimer la sélection</button></div><table><thead><tr><th><input type="checkbox" id="select-all" aria-label="Sélectionner toutes les affectations"></th><th>Pilote</th><th>Vol</th><th>Départ → arrivée</th><th>Note</th><th>Action</th></tr></thead><tbody>@forelse($assignments as $assignment)<tr><td><input class="assignment-select" type="checkbox" name="ids[]" value="{{ $assignment->id }}" aria-label="Sélectionner l’affectation de {{ $assignment->user_name }}"></td><td><strong>{{ $assignment->pilot_id }}</strong><br><small>{{ $assignment->user_name }}</small></td><td><strong>{{ $assignment->route_code ?: $assignment->flight_number }}</strong><br><small>{{ $assignment->flight_number }}</small></td><td>{{ $assignment->dpt_airport_id }} → {{ $assignment->arr_airport_id }}</td><td>{{ $assignment->notes ?: '—' }}</td><td><button class="text-button" type="submit" form="delete-assignment-{{ $assignment->id }}">Supprimer</button></td></tr>@empty<tr><td colspan="6">Aucune affectation ne correspond aux filtres.</td></tr>@endforelse</tbody></table></section></form>@foreach($assignments as $assignment)<form id="delete-assignment-{{ $assignment->id }}" method="post" action="{{ route('admin.promethee.assignments.delete',$assignment->id) }}" onsubmit="return confirm('Supprimer cette affectation ?')">@csrf @method('DELETE')</form>@endforeach
@push('scripts')<script>window.addEventListener('load',()=>{const all=document.getElementById('select-all'),items=[...document.querySelectorAll('.assignment-select')],button=document.getElementById('delete-selected');const sync=()=>{const count=items.filter(i=>i.checked).length;button.disabled=!count;button.textContent=count?`Supprimer la sélection (${count})`:'Supprimer la sélection';all.checked=!!count&&count===items.length;all.indeterminate=!!count&&count<items.length};all?.addEventListener('change',()=>{items.forEach(i=>i.checked=all.checked);sync()});items.forEach(i=>i.addEventListener('change',sync));sync()});</script>@endpush
@endsection
