@extends('promethee::layout')
@section('title','Modifier '.$airline->name)
@section('content')
<div class="ops-header compact"><div><span class="eyebrow">ADMINISTRATION · COMPAGNIES</span><h1>{{ $airline->name }}</h1><p>Identité, logo, accès pilote et état de la compagnie.</p></div><a class="button outline" href="{{ route('admin.promethee.airlines') }}">← Toutes les compagnies</a></div>
<div class="airline-edit-grid">
<section class="panel airline-brand-card"><span class="eyebrow">IDENTITÉ VISUELLE</span><div class="airline-logo-stage">@if($airline->logo)<img id="logo-preview" src="{{ filter_var($airline->logo,FILTER_VALIDATE_URL) ? $airline->logo : asset(ltrim($airline->logo,'/')) }}" alt="Logo {{ $airline->name }}">@else<div id="logo-empty">Aucun logo</div><img id="logo-preview" hidden alt="">@endif</div><strong>{{ $airline->icao }} · {{ $airline->name }}</strong><small>{{ $airline->callsign ?: 'Indicatif non renseigné' }}</small>@if($airline->logo)<form method="post" action="{{ route('admin.promethee.airlines.logo.delete',$airline) }}" onsubmit="return confirm('Supprimer le logo de cette compagnie ?')">@csrf @method('DELETE')<button class="button outline danger" type="submit">Supprimer le logo</button></form>@endif</section>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">FICHE COMPAGNIE</span><h2>Informations</h2></div><span class="tag">{{ $airline->active ? 'ACTIVE' : 'INACTIVE' }}</span></div>
<form method="post" enctype="multipart/form-data" action="{{ route('admin.promethee.airlines.update',$airline) }}" class="form-grid">@csrf @method('PUT')
<label>Nom<input name="name" required value="{{ old('name',$airline->name) }}"></label><label>ICAO<input name="icao" maxlength="5" required value="{{ old('icao',$airline->icao) }}"></label><label>IATA<input name="iata" maxlength="5" value="{{ old('iata',$airline->iata) }}"></label><label>Indicatif radio<input name="callsign" value="{{ old('callsign',$airline->callsign) }}"></label>
<label>Pays<select name="country"><option value="">—</option>@foreach($countries as $code=>$country)<option value="{{ $code }}" @selected(old('country',$airline->country)===$code)>{{ $country }}</option>@endforeach</select></label><label>Accès à partir de<input type="number" min="0" name="min_flight_hours" value="{{ old('min_flight_hours',$airline->min_flight_hours) }}"><small>Heures de vol validées requises.</small></label>
<label class="filter-wide">Logo existant / URL<input id="logo-url" name="logo" value="{{ old('logo',$airline->logo) }}" placeholder="https://… ou airline-logos/logo.png"><small>Peut pointer vers une ressource existante. Un upload ci-dessous prend priorité.</small></label>
<label class="filter-wide">Remplacer par un fichier<input id="logo-upload" type="file" name="logo_upload" accept="image/png,image/jpeg,image/webp"><small>PNG, JPG ou WebP · 2 Mo maximum.</small></label>
<label class="check"><input type="checkbox" name="active" value="1" @checked(old('active',$airline->active))> Compagnie active</label>
<div class="filter-wide form-actions"><button class="button">Enregistrer les modifications</button><a class="button outline" href="{{ route('admin.promethee.airlines') }}">Annuler</a></div></form></section></div>
@push('scripts')<script>window.addEventListener('load',()=>{const img=document.getElementById('logo-preview'),empty=document.getElementById('logo-empty'),url=document.getElementById('logo-url'),upload=document.getElementById('logo-upload');const show=src=>{if(!src)return;if(empty)empty.hidden=true;img.hidden=false;img.src=src};url.addEventListener('input',()=>show(url.value));upload.addEventListener('change',()=>{const file=upload.files&&upload.files[0];if(file)show(URL.createObjectURL(file))})});</script>@endpush
@push('styles')<style>.airline-edit-grid{display:grid;grid-template-columns:minmax(240px,.65fr) minmax(0,1.8fr);gap:18px}.airline-brand-card{align-self:start;text-align:center;display:grid;gap:14px}.airline-logo-stage{min-height:180px;border:1px dashed var(--line);border-radius:12px;display:grid;place-items:center;padding:20px;background:rgba(255,255,255,.025)}.airline-logo-stage img{max-width:100%;max-height:130px;object-fit:contain}.form-actions{display:flex;gap:10px;flex-wrap:wrap}@media(max-width:850px){.airline-edit-grid{grid-template-columns:1fr}}</style>@endpush
@endsection