<?php $__env->startSection('title','Programme des vols'); ?>
<?php $__env->startSection('content'); ?>
<div class="ops-header compact"><div><span class="eyebrow">LE RÉSEAU AIR INTER</span><h1>Programme des vols.</h1><p>Filtrer, comparer et préparer une rotation sans quitter Prométhée.</p></div><span class="tag"><?php echo e($flights->total()); ?> lignes publiées</span></div>
<form class="panel filters flight-filter" method="get">
<label class="filter-wide">Vol ou aéroport<input name="q" value="<?php echo e(request('q')); ?>" placeholder="IT123, LFPO, code ligne…"></label>
<label>Départ<select name="departure"><option value="">Tous les départs</option><?php $__currentLoopData = $mapAirports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $airport): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($airport['code']); ?>" <?php if(request('departure')===$airport['code']): echo 'selected'; endif; ?>><?php echo e($airport['code']); ?> · <?php echo e($airport['name']); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
<label>Arrivée<select name="arrival"><option value="">Toutes les arrivées</option><?php $__currentLoopData = $mapAirports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $airport): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($airport['code']); ?>" <?php if(request('arrival')===$airport['code']): echo 'selected'; endif; ?>><?php echo e($airport['code']); ?> · <?php echo e($airport['name']); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
<label>Compagnie<select name="airline_id"><option value="">Toutes</option><?php $__currentLoopData = $airlines; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $airline): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($airline->id); ?>" <?php if((string)request('airline_id')===(string)$airline->id): echo 'selected'; endif; ?>><?php echo e($airline->icao); ?> · <?php echo e($airline->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
<label>Appareil / flotte<select name="subfleet_id"><option value="">Tous</option><?php $__currentLoopData = $subfleets; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $subfleet): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($subfleet->id); ?>" <?php if((string)request('subfleet_id')===(string)$subfleet->id): echo 'selected'; endif; ?>><?php echo e($subfleet->type); ?> · <?php echo e($subfleet->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
<label>Type<select name="flight_type"><option value="">Tous</option><?php $__currentLoopData = $flightTypes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $code=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($code); ?>" <?php if(request('flight_type')===$code): echo 'selected'; endif; ?>><?php echo e($code); ?> · <?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
<label>Départ après<input name="time_from" type="time" value="<?php echo e(request('time_from')); ?>"></label><label>Départ avant<input name="time_to" type="time" value="<?php echo e(request('time_to')); ?>"></label><label>Distance min. (NM)<input name="min_distance" type="number" min="0" value="<?php echo e(request('min_distance')); ?>"></label><label>Distance max. (NM)<input name="max_distance" type="number" min="0" value="<?php echo e(request('max_distance')); ?>"></label>
<label>Trier par<select name="sort"><option value="departure" <?php if(request('sort','departure')==='departure'): echo 'selected'; endif; ?>>Heure de départ</option><option value="ident" <?php if(request('sort')==='ident'): echo 'selected'; endif; ?>>Numéro de vol</option><option value="distance" <?php if(request('sort')==='distance'): echo 'selected'; endif; ?>>Distance</option></select></label><button>Appliquer les filtres</button><a href="<?php echo e(route('promethee.flights')); ?>">Réinitialiser</a>
</form>
<section class="panel network-map-panel" aria-labelledby="network-map-title"><div class="panel-heading"><div><span class="eyebrow">SÉLECTION PAR CARTE</span><h2 id="network-map-title">Choisir l’itinéraire</h2></div><p class="map-help">Molette ou boutons +/− pour zoomer ; glissez pour vous déplacer. Cliquez un aéroport pour le départ, puis un second pour l’arrivée.</p></div><div class="map-selection" aria-live="polite"><span>Départ : <b><?php echo e(request('departure') ?: 'à sélectionner'); ?></b></span><span>Arrivée : <b><?php echo e(request('arrival') ?: 'à sélectionner'); ?></b></span><?php if(request('departure')||request('arrival')): ?><a href="<?php echo e(route('promethee.flights',request()->except(['departure','arrival','page']))); ?>">Effacer la sélection</a><?php endif; ?></div><div id="flight-network-map" class="network-map" aria-label="Carte interactive des aéroports desservis"></div><p class="map-legend"><i></i> Aéroport desservi <i class="legend-route"></i> Route correspondant aux filtres</p></section>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
(()=>{const airports=<?php echo json_encode($mapAirports, 15, 512) ?>,routes=<?php echo json_encode($mapRoutes, 15, 512) ?>,departure=<?php echo json_encode(request('departure'), 15, 512) ?>,arrival=<?php echo json_encode(request('arrival'), 15, 512) ?>,base=<?php echo json_encode(route('promethee.flights'), 15, 512) ?>;if(!window.L){document.querySelector('#flight-network-map').textContent='La bibliothèque cartographique est indisponible. Vérifiez votre connexion Internet.';return;}const map=L.map('flight-network-map',{scrollWheelZoom:true,zoomControl:true,minZoom:2,maxZoom:12}).setView([46.6,2.5],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);const points=[];const go=code=>{const q=new URLSearchParams(location.search);q.delete('page');if(!departure||arrival){q.set('departure',code);q.delete('arrival');}else if(code!==departure){q.set('departure',departure);q.set('arrival',code);}location.href=base+'?'+q.toString();};airports.forEach(a=>{const selected=a.code===departure||a.code===arrival;const marker=L.circleMarker([a.lat,a.lon],{radius:selected?8:5,weight:selected?3:1,color:'#fff',fillColor:a.code===arrival?'#d92732':'#0b5cad',fillOpacity:1}).addTo(map);marker.bindTooltip(`<b>${a.code}</b><br>${a.name}`,{direction:'top'});marker.on('click',()=>go(a.code));points.push([a.lat,a.lon]);});routes.forEach(r=>r.from&&r.to&&L.polyline([[r.from.lat,r.from.lon],[r.to.lat,r.to.lon]],{color:'#0b5cad',weight:2,opacity:.65}).addTo(map));if(points.length)map.fitBounds(points,{padding:[30,30],maxZoom:6});})();
</script>
<section class="flight-cards"><?php $__empty_1 = true; $__currentLoopData = $flights; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $flight): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><article class="panel line-card"><div class="line-card-head"><div><span class="eyebrow"><?php echo e($flight->airline?->name ?? 'Air Inter'); ?></span><h2><?php echo e($flight->ident); ?></h2></div><a class="round-link" aria-label="Préparer <?php echo e($flight->ident); ?>" href="<?php echo e(route('promethee.flights.show',$flight->id)); ?>">→</a></div><div class="airport-pair"><strong title="<?php echo e($flight->dpt_airport?->name); ?>"><?php echo e($flight->dpt_airport_id); ?></strong><i></i><strong title="<?php echo e($flight->arr_airport?->name); ?>"><?php echo e($flight->arr_airport_id); ?></strong></div><p class="muted"><?php echo e($flight->dpt_airport?->location ?: $flight->dpt_airport_id); ?> → <?php echo e($flight->arr_airport?->location ?: $flight->arr_airport_id); ?></p><dl class="line-meta"><div><dt>Départ</dt><dd><?php echo e($flight->dpt_time ?: '—'); ?></dd></div><div><dt>Arrivée</dt><dd><?php echo e($flight->arr_time ?: '—'); ?></dd></div><div><dt>Distance</dt><dd><?php echo e(number_format($flight->distance->toUnit('nmi'),0,',',' ')); ?> NM</dd></div></dl><div class="fare-chips"><?php $__empty_2 = true; $__currentLoopData = $flight->subfleets; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $subfleet): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_2 = false; ?><span><?php echo e($subfleet->type); ?></span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_2): ?><span>Flotte à confirmer</span><?php endif; ?></div></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><section class="panel empty"><h2>Aucun vol ne correspond à la recherche.</h2><p>Élargissez un filtre ou réinitialisez la recherche.</p></section><?php endif; ?></section>
<?php echo e($flights->links('pagination::bootstrap-4')); ?>

<?php $__env->stopSection(); ?>

<?php echo $__env->make('promethee::layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /home/jewe0363/promethee/modules/Promethee/Providers/../Resources/views/flights.blade.php ENDPATH**/ ?>