<?php $__env->startSection('title','Passeport pilote'); ?>
<?php $__env->startSection('content'); ?>
<div class="ops-header compact"><div><span class="eyebrow">CARNET DE VOYAGE</span><h1>Mon passeport.</h1><p>Les pays sont validés automatiquement à chaque PIREP accepté.</p></div><span class="tag"><?php echo e($countries->count()); ?> pays visités</span></div>
<?php if(DB::table('promethee_settings')->where('key','passport.map_enabled')->value('value') !== '0'): ?>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">CARTE DU MONDE</span><h2>Pays validés</h2><p>Les pays colorés correspondent à votre passeport.</p></div></div><div id="passport-map" class="network-map" aria-label="Carte des pays visités"></div></section>
<?php $__env->startPush('scripts'); ?><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>window.addEventListener('load',async()=>{const el=document.getElementById('passport-map');if(!el||!window.L)return;const visited=<?php echo json_encode($countries->pluck('country')->values(), 15, 512) ?>;const map=L.map(el,{scrollWheelZoom:false,zoomControl:true}).setView([20,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);try{const geo=await fetch('https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson').then(r=>r.json());L.geoJSON(geo,{style:f=>({color:'#ffffff',weight:1,fillColor:visited.includes(f.properties.ISO3166_1_Alpha_2)?'#0b5cad':'#b8c1c9',fillOpacity:visited.includes(f.properties.ISO3166_1_Alpha_2)?.8:.35}),onEachFeature:(f,l)=>l.bindTooltip(f.properties.ADMIN+' · '+(visited.includes(f.properties.ISO3166_1_Alpha_2)?'Validé':'Non validé'))}).addTo(map)}catch(e){el.textContent='Carte indisponible : vérifiez la connexion Internet.'}});</script><?php $__env->stopPush(); ?>
<?php endif; ?>
<section class="control-strip"><article><span>Pays visités</span><strong><?php echo e($countries->count()); ?></strong><small>Cachets distincts</small></article><article><span>Étapes internationales</span><strong><?php echo e($countries->sum('legs')); ?></strong><small>Départs et arrivées</small></article><article><span>Premier cachet</span><strong><?php echo e(optional($countries->sortBy('first_visit')->first())->first_visit ? \Carbon\Carbon::parse($countries->sortBy('first_visit')->first()->first_visit)->format('d/m/Y') : '—'); ?></strong><small>PIREP accepté</small></article></section>
<div class="two-columns"><section class="panel table-wrap"><div class="panel-heading"><div><span class="eyebrow">TAMPONS</span><h2>Pays parcourus</h2></div></div><table><thead><tr><th>Pays</th><th>1er passage</th><th>Dernier passage</th><th>Étapes</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $countries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $country): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($country->country); ?></strong></td><td><?php echo e(\Carbon\Carbon::parse($country->first_visit)->setTimezone('Europe/Paris')->format('d/m/Y')); ?></td><td><?php echo e(\Carbon\Carbon::parse($country->last_visit)->setTimezone('Europe/Paris')->format('d/m/Y')); ?></td><td><?php echo e($country->legs); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4">Aucun pays encore validé. Réalisez un vol accepté pour obtenir votre premier cachet.</td></tr><?php endif; ?></tbody></table></section><section class="panel table-wrap"><div class="panel-heading"><div><span class="eyebrow">CLASSEMENT</span><h2>Passeports les plus remplis</h2></div></div><table><thead><tr><th>#</th><th>Pilote</th><th>Pays</th></tr></thead><tbody><?php $__currentLoopData = $ranking; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $position=>$entry): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr <?php if($entry->id === $pilot->id): ?> class="selected" <?php endif; ?>><td><?php echo e($position + 1); ?></td><td><?php echo e($entry->pilot_id); ?> · <?php echo e($entry->name); ?></td><td><?php echo e($entry->countries); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></section></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('promethee::layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /home/jewe0363/promethee/modules/Promethee/Providers/../Resources/views/passport.blade.php ENDPATH**/ ?>