<?php $__env->startSection('title','Sécurité des vols'); ?>
<?php $__env->startSection('content'); ?>
<div class="page-heading no-print"><div><span class="eyebrow">APPRENDRE ENSEMBLE</span><h1>La sécurité, en perspective.</h1><p>Un regard collectif sur les vols de la compagnie. Aucun classement individuel.</p></div><form class="filters"><label>Mois<input type="month" name="month" value="<?php echo e($month); ?>" required></label><button>Afficher</button></form></div>
<div class="toolbar no-print"><button type="button" data-print>Imprimer / PDF</button><a class="button outline" href="<?php echo e(route('promethee.export',['month'=>$month])); ?>">Exporter les statistiques CSV</a><?php if (app('laratrust')->ability('admin','admin-access')) : ?><form method="post" action="<?php echo e(route('admin.promethee.safety.generate')); ?>"><?php echo csrf_field(); ?><input type="hidden" name="month" value="<?php echo e($month); ?>"><button class="outline"><?php echo e($saved ? 'Actualiser le bulletin' : 'Enregistrer le bulletin'); ?></button></form><?php endif; // app('laratrust')->ability ?></div>
<article class="bulletin">
<header class="bulletin-header"><img class="bulletin-brand-logo" src="<?php echo e($branding['url']); ?>" alt="Air Inter"><div><span class="eyebrow">CENTRE TECHNIQUE</span><p>Direction de l’Exploitation Aérienne<br><small>Technical Center — Flight Operations Department</small></p></div><span class="issue"><?php echo e(\Carbon\Carbon::parse($month.'-01')->locale('fr')->isoFormat('MMMM YYYY')); ?><br><?php echo e($saved ? 'Nº '.str_pad((string)$saved->id,2,'0',STR_PAD_LEFT) : 'Projet de bulletin'); ?></span></header>
<h1>BULLETIN DE SÉCURITÉ<br>DES VOLS</h1><h2 class="english-title">AIR INTER FLIGHT SAFETY BULLETIN</h2>
<p class="report-intro">Observer. Comprendre. Progresser.<br><span>Des statistiques anonymisées pour faire évoluer nos pratiques de simulation.</span></p>
<div class="report-summary"><strong><?php echo e($report['flights']); ?></strong><div>PIREP acceptés sur la période<br><small>Accepted flight reports · Mois civil, heure de Paris</small></div></div>
<table class="report-table"><thead><tr><th>Indicateur / Indicator</th><th>Évaluables</th><th>Dépassements</th><th>Taux</th><th>Non évaluables</th></tr></thead><tbody>
<?php $__currentLoopData = ['hard_landing'=>'Atterrissages durs¹ / Hard landings','overspeed'=>'Vols avec dépassement IAS / Flights with overspeed']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<tr><td><?php echo e($label); ?></td><td><?php echo e($report[$key]['evaluated']); ?></td><td><?php echo e($report[$key]['exceeded']); ?></td><td><?php echo e($report[$key]['evaluated'] ? number_format(100*$report[$key]['exceeded']/$report[$key]['evaluated'],1,',').' %' : '—'); ?></td><td><?php echo e($report[$key]['unknown']); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
<?php ($approach=$report['approach']); ?>
<tr><td>Approches non stabilisées à 1 000 ft²<br><small>Unstabilized approaches at 1,000 ft</small></td><td><?php echo e($approach['stable']+$approach['unstable']); ?></td><td><?php echo e($approach['unstable']); ?></td><td><?php echo e($approach['stable']+$approach['unstable'] ? number_format(100*$approach['unstable']/($approach['stable']+$approach['unstable']),1,',').' %' : '—'); ?></td><td><?php echo e($approach['unknown']); ?></td></tr>
</tbody></table>
<div class="report-details"><p><strong><?php echo e($approach['stable']); ?></strong> approches stabilisées · <strong><?php echo e($report['speed_events']); ?></strong> épisodes de dépassement IAS détectés.</p><p><strong><?php echo e($approach['flights_without_checkpoint']); ?></strong> vols sans point de contrôle exploitable à 1 000 ft.</p></div>
<section class="methodology"><h3>Lecture des indicateurs / How to read this bulletin</h3><p>Une donnée absente n’est jamais considérée comme conforme. Chaque taux utilise uniquement son nombre de cas évaluables. Plusieurs approches peuvent être comptées pour un vol avec remise de gaz.</p><p>¹ Indicateur de simulation : valeur absolue du taux d’atterrissage ≥ 600 ft/min. Ce seuil n’est pas un diagnostic structurel et ne remplace pas les limites propres à l’appareil.</p><p>² Profil de simulation v<?php echo e($report['version']); ?> : franchissement descendant de 1 000 ft AGL, deux échantillons espacés de 10 secondes maximum ; IAS entre Vref − 5 et Vref + 20 kt, descente ≤ 1 000 ft/min, inclinaison ≤ 15°, train et volets configurés, poussée stabilisée, checklist achevée et écarts localizer/glide ≤ 1 point. Les données manquantes rendent l’approche non évaluable. Ce profil concerne les approches avec guidage compatible ; les autres nécessitent un profil adapté.</p><p>Les dépassements de vitesse utilisent la limite IAS transmise par le collecteur. Les anciens PIREP sans cette télémétrie restent non évaluables pour cet indicateur. Aucun nom, identifiant pilote, numéro de vol ou horaire individuel ne figure dans ce bulletin.</p></section>
<footer class="bulletin-footer">AIR INTER · COMPAGNIE VIRTUELLE <span><?php echo e($saved ? 'Enregistré le '.$saved->updated_at : 'Aperçu calculé à la demande'); ?></span></footer>
</article>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('promethee::layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /home/jewe0363/promethee/modules/Promethee/Providers/../Resources/views/safety.blade.php ENDPATH**/ ?>