<?php $__env->startSection('title', __('common.login')); ?>
<?php $__env->startSection('content'); ?>
  <div class="login-form-heading"><h2><?php echo e(__('promethee.pilot_login')); ?></h2><p><?php echo e(__('promethee.login_intro')); ?></p></div>
  <div id="minitel-access" class="minitel-access" hidden><p><strong><?php echo e(__('promethee.minitel_access')); ?></strong> <?php echo e(__('promethee.minitel_instruction')); ?></p><label for="minitel-access-code"><?php echo e(__('promethee.service_code')); ?></label><input id="minitel-access-code" type="text" inputmode="text" autocomplete="off" autocapitalize="characters" spellcheck="false" placeholder="3615 AIR INTER"><div id="minitel-access-status" class="minitel-access-status" aria-live="polite"></div></div>
  <form method="post" action="<?php echo e(url('/login')); ?>" class="login-form">
    <?php echo csrf_field(); ?>
    <div class="field"><label for="email"><?php echo app('translator')->get('common.email'); ?> <?php echo app('translator')->get('common.or'); ?> <?php echo app('translator')->get('common.pilot_id'); ?></label><input data-auth-control type="text" name="email" id="email" value="<?php echo e(old('email')); ?>" required autofocus><?php if($errors->has('email')): ?><div class="text-danger small mt-1"><?php echo e($errors->first('email')); ?></div><?php endif; ?></div>
    <div class="field"><label for="password"><?php echo app('translator')->get('auth.password'); ?></label><input data-auth-control type="password" name="password" id="password" required><?php if($errors->has('password')): ?><div class="text-danger small mt-1"><?php echo e($errors->first('password')); ?></div><?php endif; ?></div>
    <button data-auth-control type="submit" class="login-submit"><?php echo app('translator')->get('common.login'); ?></button>
    <div class="oauth-login"><?php if(config('services.discord.enabled')): ?><a data-auth-external href="<?php echo e(route('oauth.redirect', ['provider' => 'discord'])); ?>" style="background:#738ADB"><?php echo app('translator')->get('auth.loginwith', ['provider' => 'Discord']); ?></a><?php endif; ?> <?php if(config('services.ivao.enabled')): ?><a data-auth-external href="<?php echo e(route('oauth.redirect', ['provider' => 'ivao'])); ?>" style="background:#0d2c99"><?php echo app('translator')->get('auth.loginwith', ['provider' => 'IVAO']); ?></a><?php endif; ?> <?php if(config('services.vatsim.enabled')): ?><a data-auth-external href="<?php echo e(route('oauth.redirect', ['provider' => 'vatsim'])); ?>" style="background:#29B473"><?php echo app('translator')->get('auth.loginwith', ['provider' => 'VATSIM']); ?></a><?php endif; ?></div>
    <div class="login-links"><a href="<?php echo e(url('/register')); ?>"><?php echo app('translator')->get('auth.createaccount'); ?></a><a href="<?php echo e(url('/password/reset')); ?>"><?php echo app('translator')->get('auth.forgotpassword'); ?> ?</a></div>
  </form>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('auth.login_layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /home/jewe0363/promethee/resources/views/layouts/beta/auth/login.blade.php ENDPATH**/ ?>