<?php return array_replace(require __DIR__.'/../en/promethee.php', [
    'dashboard'=>'Panel de control', 'operations'=>'Operaciones', 'flight_schedule'=>'Programa de vuelos', 'calendar'=>'Calendario', 'community'=>'Comunidad', 'latest_pireps'=>'Últimos PIREP', 'flight_safety'=>'Seguridad de vuelo', 'public_home'=>'Inicio público', 'completed_flights'=>'Vuelos realizados', 'language'=>'Idioma', 'display'=>'Pantalla', 'display_style'=>'Estilo de visualización', 'modern'=>'Moderno', 'year_2000'=>'Años 2000', 'skip_to_content'=>'Ir al contenido', 'operations_centre'=>'Centro de operaciones', 'virtual_airline'=>'Aerolínea virtual', 'pilot_area'=>'Área de piloto', 'visitor_access'=>'Acceso de visitante', 'view_my_profile'=>'Ver mi perfil', 'logout'=>'Cerrar sesión', 'read_only'=>'Solo lectura', 'login'=>'Iniciar sesión', 'register'=>'Registrarse', 'input_error'=>'Revise la información introducida', 'pilot_login'=>'Acceso de piloto', 'login_intro'=>'Acceda a su libro de vuelo y a las operaciones.', 'minitel_instruction'=>'marque el servicio antes de identificarse.', 'service_code'=>'CÓDIGO DEL SERVICIO', 'welcome_aboard'=>'Bienvenido a bordo.', 'login_welcome'=>'Entre en el espacio de piloto de Air Inter y prepare su próxima rotación.', 'powered_by'=>'Desarrollado por phpVMS', 'flight_not_found'=>'¡Vuelo no encontrado!',
    'dispatch_desk' => 'Centro de despacho', 'admin_pilots' => 'Gestión de pilotos', 'admin_ranks' => 'Gestión de rangos',
    'dashboard_page' => [
        'title' => 'Panel de control', 'eyebrow' => 'DIRECCIÓN DE OPERACIONES AÉREAS', 'heading' => 'Panel de situación Promethee.', 'intro' => 'Actividad de la red, salidas por preparar, seguridad y operaciones comerciales.',
        'paris_time' => 'HORA DE PARÍS', 'active_flights' => 'Vuelos en curso', 'open_pireps' => 'PIREPs abiertos / en pausa', 'pending' => 'Pendiente de revisión', 'admin_queue' => 'Cola de PIREPs de administración', 'today' => 'Hoy',
        'accepted_flights' => 'Vuelos aceptados', 'telemetry' => 'Telemetría', 'daily_samples' => 'Muestras de hoy', 'your_logbook' => 'Tu libro de vuelo', 'world_clocks' => 'Relojes mundiales', 'international_network' => 'RED INTERNACIONAL',
        'network_schedule' => 'PROGRAMA DE LA RED', 'upcoming_flights' => 'Próximos vuelos para reservar', 'full_schedule' => 'Programa completo', 'prepare' => 'Preparar', 'no_upcoming' => 'No hay vuelos disponibles para reservar desde tu aeropuerto base.',
        'control_post' => 'PUESTO DE CONTROL', 'quick_actions' => 'Acciones rápidas', 'operations_room' => 'Sala de operaciones', 'safety_bulletin' => 'Boletín de seguridad', 'monthly_network' => 'RED DEL MES', 'most_flown_routes' => 'Rutas más voladas', 'flights_count' => ':count vuelos',
        'no_monthly_activity' => 'No hay actividad aceptada este mes.', 'safety' => 'SEGURIDAD', 'current_bulletin' => 'Boletín actual', 'last_bulletin' => 'Último boletín registrado', 'draft' => 'Borrador', 'no_bulletin' => 'No hay boletines registrados', 'open' => 'Abrir', 'calculate' => 'Calcular',
        'your_progress' => 'TU PROGRESO', 'pilot_logbook' => 'Libro de vuelo del piloto', 'validated_flights' => 'Vuelos validados en tu libro de vuelo', 'recent_activity' => 'Actividad reciente', 'latest_accepted_pireps' => 'ÚLTIMOS PIREPs ACEPTADOS', 'view_operations_room' => 'Ver sala de operaciones', 'time' => 'Hora', 'airport' => 'Aeropuerto', 'no_accepted_pireps' => 'No hay PIREPs aceptados.',
    ],
    'navigation_welcome'=>'Bienvenida', 'navigation_pilot'=>'Área de piloto', 'navigation_company'=>'Compañía', 'navigation_operations'=>'Operaciones', 'navigation_private'=>'Privado',
    'navigation_menu'=>['settings'=>'Configuración', 'flight_map'=>'Mapa de vuelos', 'reports' => 'Mis informes', 'all_reports' => 'Todos los informes', 'my_reports' => 'Mis informes', 'bookings'=>'Mis reservas', 'downloads'=>'Descargas', 'live_flights'=>'Vuelos en tiempo real'],
    'appearance'=>'Apariencia', 'appearance_style'=>'Apariencia cromática', 'appearance_light'=>'Día', 'appearance_dark'=>'Noche',
    'company_finances' => 'Finanzas de las compañías',
]);
