@extends('promethee::layout')
@section('title','Automatisations')
@section('content')
<div class="ops-header compact"><div><span class="eyebrow">BADGES & GRADES</span><h1>Règles de progression.</h1><p>Les règles actives sont appliquées automatiquement à la validation des vols et lors des changements de statistiques. Un contrôle de sécurité repasse toutes les 5 minutes pour les critères temporels.</p></div><span class="tag">AUTOMATIQUE · AUCUNE ACTION REQUISE</span></div>
@if(session('automation_preview'))<section class="panel"><h2>{{ session('automation_preview.count') }} pilote(s) éligible(s)</h2><p>{{ implode(' · ', session('automation_preview.pilots')) ?: 'Aucun pilote ne correspond actuellement.' }}</p></section>@endif
<div class="two-columns">
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">BADGES</span><h2>Règle d’attribution</h2></div></div><form method="post" action="{{ route('admin.promethee.automation.badges.save') }}" class="form-grid rule-form" data-rule-kind="badge">@csrf<label>Badge<select name="award_id">@foreach($awards as $award)<option value="{{ $award->id }}">{{ $award->name }}</option>@endforeach</select></label>@include('promethee::admin.rule-fields')<label><input type="checkbox" name="active" value="1"> Activer dès l’enregistrement</label><div><button>Enregistrer</button> <button type="submit" formaction="{{ route('admin.promethee.automation.preview') }}" class="button outline">Prévisualiser</button></div></form><div class="route-list">@forelse($badgeRules as $rule)<div><strong>{{ optional($awards->firstWhere('id',$rule->award_id))->name ?: 'Badge supprimé' }}</strong><span>{{ strtoupper($rule->operator) }} · {{ $rule->active ? 'active' : 'brouillon' }} · {{ collect(json_decode($rule->criteria,true) ?: [])->pluck('metric')->join(', ') }}</span></div>@empty<p class="muted">Aucune règle enregistrée.</p>@endforelse</div></section>
<section class="panel" style="grid-column:1 / -1"><div class="panel-heading"><div><span class="eyebrow">GRADES</span><h2>Règle de promotion</h2></div></div><form method="post" action="{{ route('admin.promethee.automation.ranks.save') }}" class="form-grid rule-form" data-rule-kind="rank">@csrf<label>Grade<select name="rank_id">@foreach($ranks as $rank)<option value="{{ $rank->id }}">{{ $rank->name }}</option>@endforeach</select></label>@include('promethee::admin.rule-fields')<label><input type="checkbox" name="active" value="1"> Activer dès l’enregistrement</label><label><input type="checkbox" name="allow_demotion" value="1"> Autoriser une rétrogradation</label><div><button>Enregistrer</button> <button type="submit" formaction="{{ route('admin.promethee.automation.preview') }}" class="button outline">Prévisualiser</button></div></form><div class="route-list">@forelse($rankRules as $rule)<div><strong>{{ optional($ranks->firstWhere('id',$rule->rank_id))->name ?: 'Grade supprimé' }}</strong><span>{{ strtoupper($rule->operator) }} · {{ $rule->active ? 'active' : 'brouillon' }} · {{ collect(json_decode($rule->criteria,true) ?: [])->pluck('metric')->join(', ') }}</span></div>@empty<p class="muted">Aucune règle enregistrée.</p>@endforelse</div></section>
</div>
<div class="two-columns"><section class="panel"><div class="panel-heading"><div><span class="eyebrow">CATALOGUE</span><h2>Ajouter un badge</h2></div></div><form method="post" enctype="multipart/form-data" action="{{ route('admin.promethee.automation.awards.create') }}" class="form-grid">@csrf<label>Nom<input name="name" required></label><label>Image URL (optionnel)<input name="image_url" type="url"></label><label class="full">Ou envoyer une image<input name="image" type="file" accept="image/*"></label><label class="full">Description<textarea name="description" rows="3"></textarea></label><button>Ajouter le badge</button></form></section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">CATALOGUE</span><h2>Ajouter un grade</h2></div></div><form method="post" enctype="multipart/form-data" action="{{ route('admin.promethee.automation.ranks.create') }}" class="form-grid">@csrf<label>Nom<input name="name" required></label><label>Heures de référence<input name="hours" type="number" min="0" value="0" required></label><label>Image URL (optionnel)<input name="image_url" type="url"></label><label>Ou envoyer une image<input name="image" type="file" accept="image/*"></label><button>Ajouter le grade</button></form></section></div>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">CATALOGUE</span><h2>Modifier une distinction</h2></div></div><div class="two-columns">
<div><h3>Badges</h3>@foreach($awards as $award)<details class="route-list"><summary>{{ $award->name }} — modifier</summary><form method="post" enctype="multipart/form-data" action="{{ route('admin.promethee.automation.awards.update',$award) }}" class="form-grid">@csrf @method('PUT')<label>Nom<input name="name" value="{{ $award->name }}" required></label><label>Nouvelle URL d’image<input name="image_url" type="url" placeholder="{{ $award->image_url ?: 'Conserver l’image actuelle' }}"></label><label class="full">Remplacer par une image<input name="image" type="file" accept="image/*"></label><label class="full">Description<textarea name="description" rows="3">{{ $award->description }}</textarea></label><button>Enregistrer le badge</button></form></details>@endforeach</div>
<div><h3>Grades</h3>@foreach($ranks as $rank)<details class="route-list"><summary>{{ $rank->name }} — modifier</summary><form method="post" enctype="multipart/form-data" action="{{ route('admin.promethee.automation.ranks.update',$rank) }}" class="form-grid">@csrf @method('PUT')<label>Nom<input name="name" value="{{ $rank->name }}" required></label><label>Heures de référence<input name="hours" type="number" min="0" value="{{ $rank->hours }}" required></label><label>Nouvelle URL d’image<input name="image_url" type="url" placeholder="{{ $rank->image_url ?: 'Conserver l’image actuelle' }}"></label><label>Remplacer par une image<input name="image" type="file" accept="image/*"></label><button>Enregistrer le grade</button></form></details>@endforeach</div>
</div></section>
@endsection
@push('scripts')<script>window.prometheeAutomationRules={badge:@json($badgeRuleData),rank:@json($rankRuleData)};window.prometheeAutomationCatalogue={badge:@json($awardData),rank:@json($rankData)};</script>@endpush
