@extends('promethee::layout')
@section('title','Administration')
@section('content')
<div class="ops-header compact"><div><span class="eyebrow">ESPACE PROTÉGÉ</span><h1>Administration Prométhée.</h1><p>Pilotage, contrôle opérationnel et règles d’automatisation.</p></div></div>
<section class="control-strip"><article><span>Pilotes actifs</span><strong>{{ $activePilots }}</strong><small>{{ $newPilots }} nouveaux ce mois</small></article><article><span>PIREPs à traiter</span><strong>{{ $pendingPireps }}</strong><small>{{ $rejectedPireps }} rejetés ce mois</small></article><article><span>Vols validés</span><strong>{{ $acceptedPireps }}</strong><small>{{ floor($flightMinutes / 60) }} h cumulées</small></article><article><span>Événements</span><strong>{{ $activeEvents }}</strong><small>actifs</small></article></section>
<div class="three-columns"><section class="panel"><div class="panel-heading"><div><span class="eyebrow">PILOTES & PIREPS</span><h2>Contrôler</h2></div></div><div class="route-list"><a href="{{ url('/admin/users') }}">Pilotes, rôles et badges →</a><a href="{{ url('/admin/pireps') }}">Validation des PIREPs →</a><a href="{{ url('/admin/ranks') }}">Grades et promotions →</a></div></section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">RÉSEAU</span><h2>Planifier</h2></div></div><div class="route-list"><a href="{{ url('/admin/flights') }}">Vols et schedules →</a><a href="{{ route('admin.promethee.events') }}">Événements et calendrier →</a><a href="{{ url('/admin/aircraft') }}">Flotte et appareils →</a></div></section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">CONFIGURATION</span><h2>Automatiser</h2></div></div><div class="route-list"><a href="{{ route('admin.promethee.automation') }}">Règles badges et grades →</a><a href="{{ route('admin.promethee.economy') }}">Tarifs et carburant →</a><a href="{{ route('admin.identity.branding') }}">Identité visuelle →</a></div></section></div>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">MODULES PROMÉTHÉE</span><h2>Gérer les ajouts</h2></div></div><div class="three-columns"><div class="route-list"><strong>Missions & circuits</strong><span>{{ $activeMissions }} mission(s) · {{ $activeCircuits }} circuit(s)</span><a href="{{ route('admin.promethee.missions') }}">Créer et publier →</a></div><div class="route-list"><strong>Affectations mensuelles</strong><span>{{ $monthlyAssignments }} objectif(s) ce mois</span><a href="{{ route('admin.promethee.assignments') }}">Attribuer des vols →</a></div><div class="route-list"><strong>Boutique virtuelle</strong><span>{{ $shopItems }} article(s) actif(s)</span><a href="{{ route('admin.promethee.shop') }}">Catalogue et crédits →</a></div><div class="route-list"><strong>Transferts</strong><span>{{ $pendingTransfers }} demande(s) en attente</span><a href="{{ route('admin.promethee.transfers') }}">Traiter les demandes →</a></div><div class="route-list"><strong>Jumpseats</strong><span>{{ $jumpseatCount }} déplacement(s) enregistré(s)</span><a href="{{ route('admin.promethee.jumpseats') }}">Régler le prix de base →</a></div><div class="route-list"><strong>Passeport pilote</strong><span>Cachets et carte des pays</span><a href="{{ route('admin.promethee.passport') }}">Paramétrer →</a></div></div></section>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">RESSOURCES PILOTES</span><h2>Téléchargements</h2></div></div><p>Organisez les clients ACARS, les ressources de flotte, les scènes d'aéroports et les documents.</p><a class="button" href="{{ route('admin.promethee.downloads') }}">Gérer les téléchargements</a></section>
@endsection
