@extends('promethee::layout')
@section('title', 'Gestion des téléchargements')
@section('content')
<div class="ops-header compact"><div><span class="eyebrow">ADMINISTRATION</span><h1>Centre de téléchargements.</h1><p>Publiez les ressources ACARS, flotte, HUBs et documents dans Prométhée.</p></div><a class="button outline" href="{{ route('promethee.downloads') }}">Voir le centre pilote</a></div>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">NOUVELLE RESSOURCE</span><h2>Publier un téléchargement</h2></div></div><form method="post" enctype="multipart/form-data" action="{{ route('admin.promethee.downloads.store') }}" class="flight-filter">@csrf<label class="filter-wide">Nom<input name="name" value="{{ old('name') }}" required></label><label>Catégorie<select name="category"><option value="acars">ACARS</option><option value="fleet">Avions et flotte</option><option value="airports">Aéroports et HUBs</option><option value="documents">Documents</option></select></label><label>Fichier<input name="file" type="file"></label><label>ou URL<input name="url" type="url" value="{{ old('url') }}" placeholder="https://…"></label><label>Description<textarea name="description">{{ old('description') }}</textarea></label><label><input name="public" value="1" type="checkbox"> accessible sans connexion</label><button>Publier</button></form></section>
@foreach(['acars' => 'ACARS', 'fleet' => 'Avions et flotte', 'airports' => 'Aéroports et HUBs', 'documents' => 'Documents'] as $key => $title)
<section class="panel table-wrap"><div class="panel-heading"><h2>{{ $title }}</h2></div><table><thead><tr><th>Nom</th><th>Description</th><th>Source</th><th></th></tr></thead><tbody>@forelse($groups->get($key, collect()) as $file)<tr><td>{{ $file->name }}</td><td>{{ $file->description }}</td><td>{{ $file->isExternalFile ? 'URL externe' : $file->filename }}</td><td>@if(str_starts_with((string) $file->ref_model, 'Modules\\Promethee\\Download\\'))<form method="post" action="{{ route('admin.promethee.downloads.delete', $file->id) }}">@csrf @method('delete')<button class="button outline">Supprimer</button></form>@else<span class="muted">Fichier phpVMS existant</span>@endif</td></tr>@empty<tr><td colspan="4">Aucune ressource.</td></tr>@endforelse</tbody></table></section>
@endforeach
@endsection
