@extends('promethee::layout')
@section('title','ACARS Prométhée')
@section('content')
<div class="page-heading"><div><span class="eyebrow">LIAISON SOL / BORD</span><h1>Prométhée vous accompagne.</h1><p>Un même carnet de vol. Trois époques. Votre simulateur.</p></div><span class="tag">{{ $bids }} réservations</span></div>
<section class="hero acars-hero"><div><span class="tag light">LE COMPAGNON DE VOL AIR INTER</span><h2>Du premier contact<br>au dernier roulage.</h2><p>Le collecteur local transmet les positions à phpVMS<br>et conserve les échantillons en attente en cas de coupure.</p></div><div class="terminal-preview"><p>──── PROMÉTHÉE / AIR INTER ────</p><p>LIAISON SIMULATEUR <span>EN ATTENTE</span></p><p>RAPPORT DE VOL <span>À PRÉPARER</span></p><p>RÉSEAU COMPAGNIE <span>DISPONIBLE</span></p><p>CHOISIR UN VOL <span class="cursor">_</span></p></div></section>
<div class="two-columns"><section class="panel"><span class="eyebrow">AVANT LE DÉPART</span><h2>Votre poste de préparation</h2><ol class="steps"><li>Choisissez et réservez une ligne du programme.</li><li>Récupérez votre clé API dans votre profil phpVMS.</li><li>Lancez le collecteur Prométhée sur le PC du simulateur.</li><li>Ouvrez son interface locale et sélectionnez le rapport à suivre.</li></ol><a class="button" href="{{ route('promethee.flights') }}">Préparer un vol ↗</a> <a href="{{ route('frontend.profile.index') }}">Mon profil & clé API ↗</a></section>
<section class="panel"><span class="eyebrow">VOTRE AMBIANCE</span><h2>Le temps change. L’esprit reste.</h2><div class="era-cards"><button type="button" data-era-choice="minitel">01 <strong>Minitel</strong><small>Phosphore · terminal · clavier</small></button><button type="button" data-era-choice="2000">02 <strong>Années 2000</strong><small>Portail · onglets · bleu métallisé</small></button><button type="button" data-era-choice="modern">03 <strong>Moderne</strong><small>Clair · lisible · épuré</small></button></div></section></div>
<section class="panel table-wrap"><h2>Vos derniers rapports</h2><table><thead><tr><th>Vol</th><th>Départ</th><th>Arrivée</th><th>État</th><th></th></tr></thead><tbody>@forelse($recent as $p)<tr><td>{{ $p->ident }}</td><td>{{ $p->dpt_airport_id }}</td><td>{{ $p->arr_airport_id }}</td><td>{{ \App\Models\Enums\PirepState::label($p->state) }}</td><td><a href="{{ route('frontend.pireps.show',$p->id) }}">Rapport ↗</a></td></tr>@empty<tr><td colspan="5">Vos rapports apparaîtront après votre premier vol.</td></tr>@endforelse</tbody></table></section>
@endsection
