@extends('promethee::layout')
@section('title','Suivi ACARS')
@section('content')
<div class="ops-header compact"><div><span class="eyebrow">CENTRE OPÉRATIONS</span><h1>Vols en direct.</h1><p>Position, ETA calculée depuis la vitesse sol, carburant et qualité du dernier signal.</p></div><span class="tag" id="live-updated">Connexion au flux ACARS…</span></div>
<section class="panel"><div id="live-map" class="ops-leaflet-map" aria-live="polite"></div><p class="muted">Molette et glisser-déposer pour explorer la carte. Les estimations sont indicatives.</p></section>
<section class="panel table-wrap"><table><thead><tr><th>Vol</th><th>Pilote</th><th>Ligne</th><th>Altitude</th><th>IAS / GS</th><th>Reste / ETA</th><th>Signal</th></tr></thead><tbody id="live-rows"><tr><td colspan="7">Connexion au flux ACARS…</td></tr></tbody></table></section>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
(()=>{const mapNode=document.querySelector('#live-map'),rowsNode=document.querySelector('#live-rows'),updated=document.querySelector('#live-updated');if(!window.L){mapNode.textContent='La bibliothèque cartographique est indisponible.';return;}const map=L.map(mapNode,{scrollWheelZoom:true,minZoom:2,maxZoom:12}).setView([46.6,2.5],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);let layer=L.layerGroup().addTo(map);const safe=v=>String(v??'—').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const render=flights=>{layer.clearLayers();const points=[];rowsNode.innerHTML=flights.length?flights.map(f=>{const alert=(f.alerts||[]).map(a=>a.label).join(' · ')||'Signal OK';if(f.lat!==null&&f.lon!==null){const marker=L.marker([f.lat,f.lon],{icon:L.divIcon({className:'aircraft-marker',html:'✈',iconSize:[24,24]})}).addTo(layer);marker.bindPopup(`<strong>${safe(f.ident)}</strong><br>${safe(f.departure)} → ${safe(f.arrival)}<br>${f.remaining_nm??'—'} NM · ${f.eta?new Date(f.eta).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):'ETA n/a'}<br>${safe(alert)}`);points.push([f.lat,f.lon]);}return `<tr><td><strong>${safe(f.ident)}</strong></td><td>${safe(f.pilot)}</td><td>${safe(f.departure)} → ${safe(f.arrival)}</td><td>${f.altitude?Math.round(f.altitude)+' ft':'—'}</td><td>${f.ias?Math.round(f.ias)+' kt':'—'} / ${f.gs?Math.round(f.gs)+' kt':'—'}</td><td>${f.remaining_nm??'—'} NM${f.eta?' · '+new Date(f.eta).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):''}</td><td>${safe(alert)}</td></tr>`}).join(''):'<tr><td colspan="7">Aucun vol ACARS en cours.</td></tr>';if(points.length)map.fitBounds(points,{padding:[38,38],maxZoom:7});};const refresh=async()=>{try{const response=await fetch(@json(route('promethee.live.data')),{headers:{Accept:'application/json'}});if(!response.ok)throw new Error();const data=await response.json();updated.textContent='MAJ '+new Date(data.updated_at).toLocaleTimeString('fr-FR');render(data.flights||[]);}catch{updated.textContent='Flux indisponible';rowsNode.innerHTML='<tr><td colspan="7">Flux momentanément indisponible.</td></tr>';}};refresh();setInterval(refresh,10000);})();
</script>
@endsection
