@extends('promethee::layout')
@section('title','Passeport pilote')
@section('content')
<div class="ops-header compact"><div><span class="eyebrow">CARNET DE VOYAGE</span><h1>Mon passeport.</h1><p>Les pays sont validés automatiquement à chaque PIREP accepté.</p></div><span class="tag">{{ $countries->count() }} pays visités</span></div>
@if(DB::table('promethee_settings')->where('key','passport.map_enabled')->value('value') !== '0')
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">CARTE DU MONDE</span><h2>Pays validés</h2><p>Les pays colorés correspondent à votre passeport.</p></div></div><div id="passport-map" class="network-map" aria-label="Carte des pays visités"></div></section>
@push('scripts')<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>window.addEventListener('load',async()=>{const el=document.getElementById('passport-map');if(!el||!window.L)return;const visited=@json($countries->pluck('country')->values());const map=L.map(el,{scrollWheelZoom:false,zoomControl:true}).setView([20,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);try{const geo=await fetch('https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson').then(r=>r.json());L.geoJSON(geo,{style:f=>({color:'#ffffff',weight:1,fillColor:visited.includes(f.properties.ISO3166_1_Alpha_2)?'#0b5cad':'#b8c1c9',fillOpacity:visited.includes(f.properties.ISO3166_1_Alpha_2)?.8:.35}),onEachFeature:(f,l)=>l.bindTooltip(f.properties.ADMIN+' · '+(visited.includes(f.properties.ISO3166_1_Alpha_2)?'Validé':'Non validé'))}).addTo(map)}catch(e){el.textContent='Carte indisponible : vérifiez la connexion Internet.'}});</script>@endpush
@endif
<section class="control-strip"><article><span>Pays visités</span><strong>{{ $countries->count() }}</strong><small>Cachets distincts</small></article><article><span>Étapes internationales</span><strong>{{ $countries->sum('legs') }}</strong><small>Départs et arrivées</small></article><article><span>Premier cachet</span><strong>{{ optional($countries->sortBy('first_visit')->first())->first_visit ? \Carbon\Carbon::parse($countries->sortBy('first_visit')->first()->first_visit)->format('d/m/Y') : '—' }}</strong><small>PIREP accepté</small></article></section>
<div class="two-columns"><section class="panel table-wrap"><div class="panel-heading"><div><span class="eyebrow">TAMPONS</span><h2>Pays parcourus</h2></div></div><table><thead><tr><th>Pays</th><th>1er passage</th><th>Dernier passage</th><th>Étapes</th></tr></thead><tbody>@forelse($countries as $country)<tr><td><strong>{{ $country->country }}</strong></td><td>{{ \Carbon\Carbon::parse($country->first_visit)->setTimezone('Europe/Paris')->format('d/m/Y') }}</td><td>{{ \Carbon\Carbon::parse($country->last_visit)->setTimezone('Europe/Paris')->format('d/m/Y') }}</td><td>{{ $country->legs }}</td></tr>@empty<tr><td colspan="4">Aucun pays encore validé. Réalisez un vol accepté pour obtenir votre premier cachet.</td></tr>@endforelse</tbody></table></section><section class="panel table-wrap"><div class="panel-heading"><div><span class="eyebrow">CLASSEMENT</span><h2>Passeports les plus remplis</h2></div></div><table><thead><tr><th>#</th><th>Pilote</th><th>Pays</th></tr></thead><tbody>@foreach($ranking as $position=>$entry)<tr @if($entry->id === $pilot->id) class="selected" @endif><td>{{ $position + 1 }}</td><td>{{ $entry->pilot_id }} · {{ $entry->name }}</td><td>{{ $entry->countries }}</td></tr>@endforeach</tbody></table></section></div>
@endsection
