@extends('promethee::layout')
@section('title','La communauté')
@section('content')
<div class="page-heading"><div><span class="eyebrow">UNE HISTOIRE D’ÉQUIPAGE</span><h1>Ceux qui font Air Inter.</h1><p>Les pilotes d’aujourd’hui, ceux qui ont écrit les chapitres précédents, et ceux dont nous honorons la mémoire.</p></div></div>
@php($canManage = auth()->user()?->ability('admin','admin-access') ?? false)
<div class="tabs">@foreach(['actif'=>'Pilotes actifs','ancien'=>'Les anciens','heaven'=>'En mémoire'] as $key=>$label)<a @class(['active'=>$status===$key]) href="{{ route('promethee.pilots',['status'=>$key]) }}">{{ $label }}</a>@endforeach</div>
@if($status === 'heaven')
<section class="memorial-intro"><span class="eyebrow">EN MÉMOIRE</span><h2>Ils ont compté pour Air Inter.</h2><p>Un espace de respect et de transmission, consacré aux membres disparus et à leur histoire.</p></section>
@endif
@if($status !== 'heaven')
<form class="panel filters directory-filter" method="get"><input type="hidden" name="status" value="{{ $status }}"><label>Rechercher<input name="q" value="{{ request('q') }}" placeholder="Nom, matricule, e-mail"></label><label>Compagnie<select name="airline_id"><option value="">Toutes les compagnies</option>@foreach($airlines as $airline)<option value="{{ $airline->id }}" @selected((string) request('airline_id') === (string) $airline->id)>{{ $airline->icao }} · {{ $airline->name }}</option>@endforeach</select></label><label>Grade<select name="rank_id"><option value="">Tous les grades</option>@foreach($ranks as $rank)<option value="{{ $rank->id }}" @selected((string) request('rank_id') === (string) $rank->id)>{{ $rank->name }}</option>@endforeach</select></label><button>Filtrer</button><a href="{{ route('promethee.pilots',['status'=>$status]) }}">Réinitialiser</a></form>
@endif
<div class="pilot-grid @if($status === 'heaven') memorial-grid @endif">@forelse($pilots as $pilot)<article class="panel pilot-card @if($status === 'heaven') memorial-card @endif">@if($status === 'heaven' && $pilot->memorial_portrait_url)<img class="memorial-portrait" src="{{ $pilot->memorial_portrait_url }}" alt="Portrait de {{ $pilot->name }}">@else<div class="avatar-text">{{ mb_substr($pilot->name,0,1) }}</div>@endif<span class="eyebrow">{{ $pilot->ident }}</span><h2>{{ $pilot->name }}</h2><p>{{ $pilot->rank?->name ?? ($status === 'heaven' ? 'Heaven' : 'Sans grade') }}</p>@if($status === 'heaven')<p class="memorial-tribute">{{ $pilot->memorial_tribute ?: 'Hommage à venir.' }}</p>@else<div class="pilot-numbers"><span><b>{{ $pilot->flights }}</b> vols</span><span><b>{{ round(($pilot->flight_time ?? 0)/60) }}</b> heures</span></div><a href="{{ route('promethee.pilots.show',$pilot->id) }}">Fiche Prométhée →</a>@endif
@if($canManage)<details class="memorial-admin"><summary>Administrer cette fiche</summary><form class="member-form memorial-form" method="post" enctype="multipart/form-data" action="{{ route('admin.promethee.pilots.save',$pilot->id) }}">@csrf<label>Classement<select name="status"><option value="actif" @selected($pilot->member_status==='actif')>Actif</option><option value="ancien" @selected($pilot->member_status==='ancien')>Ancien</option><option value="heaven" @selected($pilot->member_status==='heaven')>En mémoire · Heaven</option></select></label><label>Portrait (URL)<input name="memorial_portrait_url" type="url" value="{{ $pilot->memorial_portrait_url }}" placeholder="https://…"></label><label>ou portrait à envoyer<input name="memorial_portrait" type="file" accept="image/*"></label><label class="full">Hommage de l’administration<textarea name="memorial_tribute" rows="5" placeholder="Son parcours, ses contributions, le souvenir que vous souhaitez partager…">{{ $pilot->memorial_tribute }}</textarea></label><button>Enregistrer</button></form></details>@endif</article>@empty<div class="panel empty"><h2>Cette page reste à écrire.</h2><p>Aucun pilote dans cette catégorie.</p></div>@endforelse</div>
{{ $pilots->links('pagination::bootstrap-4') }}
@if($status !== 'heaven')
<section class="community-library panel"><div class="panel-heading"><div><span class="eyebrow">RESSOURCES PARTAGÉES</span><h2>Documents de la communauté</h2></div><a class="button outline" href="{{ route('promethee.downloads.category','documents') }}">Voir la bibliothèque</a></div><p>Procédures, sécurité des vols et ressources utiles, présentées pour être consultées simplement avant le départ.</p><div class="document-card-grid">@forelse($communityDocuments as $file)<article class="document-card"><span class="file-mark">DOC</span><div><strong>{{ $file->name }}</strong><p>{{ $file->description ?: 'Document de référence Air Inter.' }}</p></div><a href="{{ route('promethee.downloads.download',$file->id) }}" aria-label="Ouvrir {{ $file->name }}">Ouvrir →</a></article>@empty<p class="empty">Les documents publiés par l’administration apparaîtront ici.</p>@endforelse</div></section>
@endif
@endsection
