@extends('promethee::layout')
@section('title','Relecture de vol')
@section('content')
<div class="ops-header compact"><div><span class="eyebrow">RETOUR D’EXPÉRIENCE</span><h1>{{ $pirep->ident }}</h1><p>{{ $pirep->dpt_airport_id }} → {{ $pirep->arr_airport_id }} · {{ $pirep->user?->name }}</p></div><span class="tag">Score {{ $score['score'] }}/100</span></div>
<section class="control-strip"><article><span>Échantillons</span><strong>{{ $samples->count() }}</strong><small>Trace enregistrée</small></article><article><span>Atterrissage</span><strong>{{ $pirep->landing_rate ? number_format($pirep->landing_rate,0,',',' ') : '—' }}</strong><small>ft/min</small></article><article><span>Survitesse</span><strong>{{ $analysis['overspeed'] === null ? 'n/a' : ($analysis['overspeed'] ? 'Oui' : 'Non') }}</strong><small>{{ $analysis['speed_events'] }} événement(s)</small></article><article><span>Approche</span><strong>{{ count($analysis['approaches']) }}</strong><small>Checkpoint(s) évalué(s)</small></article></section>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">TRACE ET CURSEUR</span><h2>Relecture chronologique</h2></div><input id="replay-range" aria-label="Position dans le vol" type="range" min="0" max="{{ max(0,$samples->count()-1) }}" value="0"></div><div id="replay-map" class="ops-leaflet-map"></div><p id="replay-detail" class="mono muted"></p></section>
<div class="two-columns"><section class="panel"><div class="panel-heading"><div><span class="eyebrow">ÉVÉNEMENTS DÉTECTÉS</span><h2>Phases de vol</h2></div></div>@forelse($score['events'] as $event)<article class="event"><time>{{ \Carbon\Carbon::parse($event['at'])->setTimezone('Europe/Paris')->format('H:i:s') }}</time><h3>{{ $event['type'] }}</h3><p>{{ $event['detail'] }}</p></article>@empty<p class="empty">Aucune phase ne peut être confirmée : la télémétrie est incomplète.</p>@endforelse</section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">SCORE EXPLICABLE</span><h2>Qualité du vol</h2></div></div>@forelse($score['items'] as $item)<article class="event"><h3>{{ $item['label'] }} · {{ $item['score'] }}/{{ $item['max'] }}</h3><p>{{ $item['detail'] }}</p></article>@empty<p class="empty">Aucun indicateur ne peut être calculé sans données correspondantes.</p>@endforelse</section></div>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
(()=>{const samples=@json($samples),mapNode=document.querySelector('#replay-map'),detail=document.querySelector('#replay-detail'),range=document.querySelector('#replay-range');if(!samples.length){mapNode.textContent='Aucune télémétrie disponible.';return;}if(!window.L){mapNode.textContent='La bibliothèque cartographique est indisponible.';return;}const valid=samples.filter(s=>Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lon)));const map=L.map(mapNode,{scrollWheelZoom:true,minZoom:2,maxZoom:14});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);const trace=valid.map(s=>[Number(s.lat),Number(s.lon)]);if(trace.length){L.polyline(trace,{color:'#155eef',weight:3,opacity:.75}).addTo(map);map.fitBounds(trace,{padding:[35,35],maxZoom:9});}else map.setView([46.6,2.5],5);const aircraft=L.marker(trace[0]||[46.6,2.5],{icon:L.divIcon({className:'aircraft-marker',html:'✈',iconSize:[24,24]})}).addTo(map);const draw=()=>{const s=samples[Number(range.value)]||samples[0];if(Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lon)))aircraft.setLatLng([Number(s.lat),Number(s.lon)]);detail.textContent=`${s.recorded_at} · ${Number(s.altitude_msl||0).toFixed(0)} ft · IAS ${Number(s.ias||0).toFixed(0)} kt · VS ${Number(s.vs||0).toFixed(0)} ft/min · carburant ${Number(s.fuel||0).toFixed(0)}`;};range.addEventListener('input',draw);draw();})();
</script>
@endsection
