<?php return array_replace(require __DIR__.'/../en/promethee.php', [
    'dashboard'=>'Cruscotto', 'operations'=>'Operazioni', 'flight_schedule'=>'Programma voli', 'calendar'=>'Calendario', 'community'=>'Comunità', 'latest_pireps'=>'Ultimi PIREP', 'flight_safety'=>'Sicurezza del volo', 'public_home'=>'Home pubblica', 'completed_flights'=>'Voli effettuati', 'language'=>'Lingua', 'display'=>'Schermo', 'display_style'=>'Stile di visualizzazione', 'modern'=>'Moderno', 'year_2000'=>'Anni 2000', 'skip_to_content'=>'Vai al contenuto', 'operations_centre'=>'Centro operativo', 'virtual_airline'=>'Compagnia aerea virtuale', 'pilot_area'=>'Area pilota', 'visitor_access'=>'Accesso visitatore', 'view_my_profile'=>'Visualizza il mio profilo', 'logout'=>'Esci', 'read_only'=>'Sola lettura', 'login'=>'Accedi', 'register'=>'Registrati', 'input_error'=>'Controlla i dati inseriti', 'pilot_login'=>'Accesso pilota', 'login_intro'=>'Accedi al tuo registro di volo e alle operazioni.', 'minitel_instruction'=>'componi il servizio prima di accedere.', 'service_code'=>'CODICE DEL SERVIZIO', 'welcome_aboard'=>'Benvenuto a bordo.', 'login_welcome'=>'Entra nell’area pilota Air Inter e prepara la tua prossima rotazione.', 'powered_by'=>'Offerto da phpVMS', 'flight_not_found'=>'Volo non trovato!',
    'dispatch_desk' => 'Centro dispatch', 'admin_pilots' => 'Gestione piloti', 'admin_ranks' => 'Gestione gradi',
    'dashboard_page' => [
        'title' => 'Cruscotto', 'eyebrow' => 'DIREZIONE DELLE OPERAZIONI AEREE', 'heading' => 'Quadro della situazione Promethee.', 'intro' => 'Attività della rete, partenze da preparare, sicurezza e operazioni commerciali.',
        'paris_time' => 'ORA DI PARIGI', 'active_flights' => 'Voli in corso', 'open_pireps' => 'PIREPs aperti / in pausa', 'pending' => 'Da esaminare', 'admin_queue' => 'Coda PIREP amministratore', 'today' => 'Oggi',
        'accepted_flights' => 'Voli accettati', 'telemetry' => 'Telemetria', 'daily_samples' => 'Campioni di oggi', 'your_logbook' => 'Il tuo diario di volo', 'world_clocks' => 'Orologi mondiali', 'international_network' => 'RETE INTERNAZIONALE',
        'network_schedule' => 'PROGRAMMA DELLA RETE', 'upcoming_flights' => 'Prossimi voli da prenotare', 'full_schedule' => 'Programma completo', 'prepare' => 'Preparare', 'no_upcoming' => 'Nessun volo disponibile da prenotare dal tuo aeroporto base.',
        'control_post' => 'POSTAZIONE DI CONTROLLO', 'quick_actions' => 'Azioni rapide', 'operations_room' => 'Sala operativa', 'safety_bulletin' => 'Bollettino di sicurezza', 'monthly_network' => 'RETE DEL MESE', 'most_flown_routes' => 'Rotte più volate', 'flights_count' => ':count voli',
        'no_monthly_activity' => 'Nessuna attività accettata questo mese.', 'safety' => 'SICUREZZA', 'current_bulletin' => 'Bollettino attuale', 'last_bulletin' => 'Ultimo bollettino registrato', 'draft' => 'Bozza', 'no_bulletin' => 'Nessun bollettino registrato', 'open' => 'Aprire', 'calculate' => 'Calcolare',
        'your_progress' => 'I TUOI PROGRESSI', 'pilot_logbook' => 'Diario di volo del pilota', 'validated_flights' => 'Voli convalidati nel tuo diario di volo', 'recent_activity' => 'Attività recente', 'latest_accepted_pireps' => 'ULTIMI PIREP ACCETTATI', 'view_operations_room' => 'Visualizza la sala operativa', 'time' => 'Ora', 'airport' => 'Aeroporto', 'no_accepted_pireps' => 'Nessun PIREP accettato.',
    ],
    'navigation_welcome'=>'Benvenuto', 'navigation_pilot'=>'Area pilota', 'navigation_company'=>'Compagnia', 'navigation_operations'=>'Operazioni', 'navigation_private'=>'Privato',
    'navigation_menu'=>['settings'=>'Impostazioni', 'flight_map'=>'Mappa dei voli', 'reports' => 'I miei rapporti', 'all_reports' => 'Tutti i rapporti', 'my_reports' => 'I miei rapporti', 'bookings'=>'Le mie prenotazioni', 'downloads'=>'Download', 'live_flights'=>'Voli in tempo reale'],
    'appearance'=>'Aspetto', 'appearance_style'=>'Aspetto cromatico', 'appearance_light'=>'Giorno', 'appearance_dark'=>'Notte',
    'company_finances' => 'Finanze delle compagnie',
]);
