<?php return array_replace(require __DIR__.'/../en/promethee.php', [
    'dashboard'=>'Kontrol paneli', 'operations'=>'Operasyonlar', 'flight_schedule'=>'Uçuş programı', 'calendar'=>'Takvim', 'community'=>'Topluluk', 'latest_pireps'=>'Son PIREP’ler', 'flight_safety'=>'Uçuş güvenliği', 'public_home'=>'Genel ana sayfa', 'completed_flights'=>'Tamamlanan uçuşlar', 'language'=>'Dil', 'display'=>'Ekran', 'display_style'=>'Görüntü stili', 'modern'=>'Modern', 'year_2000'=>'2000’ler', 'skip_to_content'=>'İçeriğe geç', 'operations_centre'=>'Operasyon merkezi', 'virtual_airline'=>'Sanal havayolu', 'pilot_area'=>'Pilot alanı', 'visitor_access'=>'Ziyaretçi erişimi', 'view_my_profile'=>'Profilimi görüntüle', 'logout'=>'Çıkış yap', 'read_only'=>'Salt okunur', 'login'=>'Giriş yap', 'register'=>'Kayıt ol', 'input_error'=>'Lütfen girilen bilgileri kontrol edin', 'pilot_login'=>'Pilot girişi', 'login_intro'=>'Uçuş günlüğünüze ve operasyonlara erişin.', 'minitel_instruction'=>'giriş yapmadan önce hizmeti arayın.', 'service_code'=>'HİZMET KODU', 'welcome_aboard'=>'Uçağa hoş geldiniz.', 'login_welcome'=>'Air Inter pilot alanına girin ve sonraki rotasyonunuzu hazırlayın.', 'powered_by'=>'phpVMS tarafından desteklenmektedir', 'flight_not_found'=>'Uçuş bulunamadı!',
    'dashboard_page' => [
        'title' => 'Kontrol paneli', 'eyebrow' => 'HAVA OPERASYONLARI YÖNETİMİ', 'heading' => 'Promethee durum panosu.', 'intro' => 'Ağ etkinliği, hazırlanacak kalkışlar, emniyet ve ticari operasyonlar.',
        'paris_time' => 'PARİS SAATİ', 'active_flights' => 'Devam eden uçuşlar', 'open_pireps' => 'Açık / duraklatılmış PIREP’ler', 'pending' => 'İncelenecek', 'admin_queue' => 'Yönetici PIREP kuyruğu', 'today' => 'Bugün',
        'accepted_flights' => 'Kabul edilen uçuşlar', 'telemetry' => 'Telemetri', 'daily_samples' => 'Bugünün örnekleri', 'your_logbook' => 'Uçuş günlüğünüz', 'world_clocks' => 'Dünya saatleri', 'international_network' => 'ULUSLARARASI AĞ',
        'network_schedule' => 'AĞ PROGRAMI', 'upcoming_flights' => 'Rezerve edilebilecek uçuşlar', 'full_schedule' => 'Tüm program', 'prepare' => 'Hazırla', 'no_upcoming' => 'Ana havalimanınızdan rezerve edilebilecek uçuş yok.',
        'control_post' => 'KONTROL NOKTASI', 'quick_actions' => 'Hızlı işlemler', 'operations_room' => 'Operasyon merkezi', 'safety_bulletin' => 'Emniyet bülteni', 'monthly_network' => 'AYLIK AĞ', 'most_flown_routes' => 'En çok uçulan rotalar', 'flights_count' => ':count uçuş',
        'no_monthly_activity' => 'Bu ay kabul edilmiş etkinlik yok.', 'safety' => 'EMNİYET', 'current_bulletin' => 'Güncel bülten', 'last_bulletin' => 'Son kaydedilen bülten', 'draft' => 'Taslak', 'no_bulletin' => 'Kayıtlı bülten yok', 'open' => 'Aç', 'calculate' => 'Hesapla',
        'your_progress' => 'İLERLEMENİZ', 'pilot_logbook' => 'Pilot uçuş günlüğü', 'validated_flights' => 'Uçuş günlüğünüzde doğrulanan uçuşlar', 'recent_activity' => 'Son etkinlik', 'latest_accepted_pireps' => 'SON KABUL EDİLEN PIREP’LER', 'view_operations_room' => 'Operasyon merkezini görüntüle', 'time' => 'Saat', 'airport' => 'Havalimanı', 'no_accepted_pireps' => 'Kabul edilmiş PIREP yok.',
    ],
    'navigation_welcome'=>'Hoş geldiniz', 'navigation_pilot'=>'Pilot alanı', 'navigation_company'=>'Havayolu', 'navigation_operations'=>'Operasyonlar', 'navigation_private'=>'Özel',
    'navigation_menu'=>['settings'=>'Ayarlar', 'flight_map'=>'Uçuş haritası', 'reports'=>'Raporlarım', 'bookings'=>'Rezervasyonlarım', 'downloads'=>'İndirilenler', 'live_flights'=>'Canlı uçuşlar'],
    'appearance'=>'Görünüm', 'appearance_style'=>'Renk görünümü', 'appearance_light'=>'Gündüz', 'appearance_dark'=>'Gece',
]);
