<?php return array_replace(require __DIR__.'/../en/promethee.php', [
    'dashboard'=>'Painel', 'operations'=>'Operações', 'flight_schedule'=>'Programação de voos', 'calendar'=>'Calendário', 'community'=>'Comunidade', 'latest_pireps'=>'Últimos PIREPs', 'flight_safety'=>'Segurança de voo', 'public_home'=>'Página pública', 'completed_flights'=>'Voos realizados', 'language'=>'Idioma', 'display'=>'Tela', 'display_style'=>'Estilo de exibição', 'modern'=>'Moderno', 'year_2000'=>'Anos 2000', 'skip_to_content'=>'Ir para o conteúdo', 'operations_centre'=>'Centro de operações', 'virtual_airline'=>'Companhia aérea virtual', 'pilot_area'=>'Área do piloto', 'visitor_access'=>'Acesso de visitante', 'view_my_profile'=>'Ver meu perfil', 'logout'=>'Sair', 'read_only'=>'Somente leitura', 'login'=>'Entrar', 'register'=>'Cadastrar-se', 'input_error'=>'Verifique as informações inseridas', 'pilot_login'=>'Acesso do piloto', 'login_intro'=>'Acesse seu diário de voo e as operações.', 'minitel_instruction'=>'disque o serviço antes de se identificar.', 'service_code'=>'CÓDIGO DO SERVIÇO', 'welcome_aboard'=>'Bem-vindo a bordo.', 'login_welcome'=>'Entre no espaço do piloto Air Inter e prepare sua próxima rota.', 'powered_by'=>'Desenvolvido por phpVMS', 'flight_not_found'=>'Voo não encontrado!',
    'dashboard_page' => [
        'title' => 'Painel', 'eyebrow' => 'DIREÇÃO DE OPERAÇÕES AÉREAS', 'heading' => 'Painel de situação Promethee.', 'intro' => 'Atividade da rede, partidas a preparar, segurança e operações comerciais.',
        'paris_time' => 'HORA DE PARIS', 'active_flights' => 'Voos em andamento', 'open_pireps' => 'PIREPs abertos / pausados', 'pending' => 'A revisar', 'admin_queue' => 'Fila de PIREPs da administração', 'today' => 'Hoje',
        'accepted_flights' => 'Voos aceitos', 'telemetry' => 'Telemetria', 'daily_samples' => 'Amostras de hoje', 'your_logbook' => 'Seu diário de voo', 'world_clocks' => 'Relógios mundiais', 'international_network' => 'REDE INTERNACIONAL',
        'network_schedule' => 'PROGRAMAÇÃO DA REDE', 'upcoming_flights' => 'Próximos voos para reservar', 'full_schedule' => 'Programação completa', 'prepare' => 'Preparar', 'no_upcoming' => 'Nenhum voo disponível para reserva a partir do seu aeroporto base.',
        'control_post' => 'POSTO DE CONTROLE', 'quick_actions' => 'Ações rápidas', 'operations_room' => 'Sala de operações', 'safety_bulletin' => 'Boletim de segurança', 'monthly_network' => 'REDE DO MÊS', 'most_flown_routes' => 'Rotas mais voadas', 'flights_count' => ':count voos',
        'no_monthly_activity' => 'Nenhuma atividade aceita neste mês.', 'safety' => 'SEGURANÇA', 'current_bulletin' => 'Boletim atual', 'last_bulletin' => 'Último boletim registrado', 'draft' => 'Rascunho', 'no_bulletin' => 'Nenhum boletim registrado', 'open' => 'Abrir', 'calculate' => 'Calcular',
        'your_progress' => 'SEU PROGRESSO', 'pilot_logbook' => 'Diário de voo do piloto', 'validated_flights' => 'Voos validados no seu diário de voo', 'recent_activity' => 'Atividade recente', 'latest_accepted_pireps' => 'ÚLTIMOS PIREPs ACEITOS', 'view_operations_room' => 'Ver sala de operações', 'time' => 'Hora', 'airport' => 'Aeroporto', 'no_accepted_pireps' => 'Nenhum PIREP aceito.',
    ],
    'navigation_welcome'=>'Boas-vindas', 'navigation_pilot'=>'Área do piloto', 'navigation_company'=>'Companhia', 'navigation_operations'=>'Operações', 'navigation_private'=>'Privado',
    'navigation_menu'=>['settings'=>'Configurações', 'flight_map'=>'Mapa de voos', 'reports' => 'Meus relatórios', 'all_reports' => 'Todos os relatórios', 'my_reports' => 'Meus relatórios', 'bookings'=>'Minhas reservas', 'downloads'=>'Downloads', 'live_flights'=>'Voos em tempo real'],
    'appearance'=>'Aparência', 'appearance_style'=>'Aparência de cores', 'appearance_light'=>'Dia', 'appearance_dark'=>'Noite',
]);
